pragma Singleton

import Quickshell

// GENERATED by tools/gen-icon-metrics.sh - do not edit by hand.
//
// The ink box of every glyph Common/Icons.qml names, in units of 1/1000 em:
// `w`/`h` are its size, `cx`/`cy` the centre of the ink measured from the pen
// origin (x rightwards, y up from the baseline). Widgets/Icon.qml scales each
// glyph so max(w, h) fills its box and puts (cx, cy) at the box's centre.
//
// Measured from: /nix/store/n22vjizi4q761ar31c2w2y7d0gsnc5y4-berkeley-mono-1.0.0/share/fonts/truetype/BerkeleyMonoNerdFont-Regular.ttf
Singleton {
    // Used for a glyph nobody measured - a square filling the cell, which is
    // what setting a font size and hoping would have given anyway.
    readonly property var fallback: ({
        w: 1000,
        h: 1000,
        cx: 500,
        cy: 500
    })

    readonly property var ink: ({
        "󰂎": { w: 600, h: 998, cx: 300, cy: 356 },  // U+F008E battery-outline
        "󰁺": { w: 600, h: 998, cx: 300, cy: 356 },  // U+F007A battery-10
        "󰁻": { w: 600, h: 998, cx: 300, cy: 356 },  // U+F007B battery-20
        "󰁼": { w: 600, h: 998, cx: 300, cy: 356 },  // U+F007C battery-30
        "󰁽": { w: 600, h: 998, cx: 300, cy: 356 },  // U+F007D battery-40
        "󰁾": { w: 600, h: 998, cx: 300, cy: 356 },  // U+F007E battery-50
        "󰁿": { w: 600, h: 998, cx: 300, cy: 356 },  // U+F007F battery-60
        "󰂀": { w: 600, h: 998, cx: 300, cy: 356 },  // U+F0080 battery-70
        "󰂁": { w: 600, h: 998, cx: 300, cy: 356 },  // U+F0081 battery-80
        "󰂂": { w: 600, h: 998, cx: 300, cy: 356 },  // U+F0082 battery-90
        "󰁹": { w: 600, h: 998, cx: 300, cy: 356 },  // U+F0079 battery
        "": { w: 600, h: 1114, cx: 301, cy: 356 },  // U+0F0E7 bolt
        "󰂑": { w: 600, h: 998, cx: 300, cy: 356 },  // U+F0091 battery-unknown
        "󰤯": { w: 600, h: 476, cx: 300, cy: 356 },  // U+F092F wifi-strength-outline
        "󰤟": { w: 600, h: 476, cx: 300, cy: 356 },  // U+F091F wifi-strength-1
        "󰤢": { w: 600, h: 476, cx: 300, cy: 356 },  // U+F0922 wifi-strength-2
        "󰤥": { w: 600, h: 476, cx: 300, cy: 356 },  // U+F0925 wifi-strength-3
        "󰤨": { w: 600, h: 476, cx: 300, cy: 356 },  // U+F0928 wifi-strength-4
        "󰤮": { w: 600, h: 516, cx: 300, cy: 356 },  // U+F092E wifi-strength-off-outline
        "󰀂": { w: 600, h: 574, cx: 300, cy: 356 },  // U+F0002 access-point-network
        "󰕿": { w: 600, h: 1068, cx: 300, cy: 356 },  // U+F057F volume-low
        "󰖀": { w: 600, h: 714, cx: 300, cy: 356 },  // U+F0580 volume-medium
        "󰕾": { w: 600, h: 584, cx: 300, cy: 356 },  // U+F057E volume-high
        "󰝟": { w: 600, h: 506, cx: 300, cy: 356 },  // U+F075F volume-mute
        "󰋋": { w: 600, h: 634, cx: 300, cy: 356 },  // U+F02CB headphones.1
        "󰋎": { w: 600, h: 734, cx: 300, cy: 356 },  // U+F02CE headset
        "󰂯": { w: 600, h: 944, cx: 300, cy: 356 },  // U+F00AF bluetooth
        "󰂱": { w: 600, h: 666, cx: 300, cy: 356 },  // U+F00B1 bluetooth-connect
        "󰂲": { w: 600, h: 748, cx: 300, cy: 356 },  // U+F00B2 bluetooth-off
        "󰦝": { w: 600, h: 734, cx: 300, cy: 356 },  // U+F099D shield-lock.1
        "󰰜": { w: 600, h: 600, cx: 300, cy: 356 },  // U+F0C1C alpha-q-circle
        "󰨛": { w: 600, h: 360, cx: 300, cy: 356 },  // U+F0A1B vhs
        "󰪡": { w: 600, h: 600, cx: 300, cy: 356 },  // U+F0AA1 circle-slice-4
        "󰀨": { w: 600, h: 600, cx: 300, cy: 356 },  // U+F0028 alert-circle
        "󰗠": { w: 600, h: 600, cx: 300, cy: 356 },  // U+F05E0 check-circle.1
        "󰍬": { w: 600, h: 816, cx: 300, cy: 356 },  // U+F036C microphone.1
        "󰍭": { w: 600, h: 632, cx: 300, cy: 356 },  // U+F036D microphone-off
        "󰍉": { w: 600, h: 600, cx: 300, cy: 356 },  // U+F0349 magnify
        "󰣆": { w: 600, h: 544, cx: 300, cy: 356 },  // U+F08C6 application
        "󰆒": { w: 600, h: 732, cx: 300, cy: 356 },  // U+F0192 content-paste
        "󰋩": { w: 600, h: 600, cx: 300, cy: 356 },  // U+F02E9 image.1
        "󰅂": { w: 600, h: 970, cx: 300, cy: 356 },  // U+F0142 chevron-right.2
        "󰏘": { w: 600, h: 600, cx: 300, cy: 356 },  // U+F03D8 palette
        "󰍪": { w: 600, h: 600, cx: 300, cy: 356 },  // U+F036A message-text-outline
        "󰃬": { w: 600, h: 858, cx: 300, cy: 356 }  // U+F00EC calculator
    })
}
