pragma Singleton

import Quickshell

// GENERATED by tools/gen-icon-metrics.sh - do not edit by hand.
//
// The ink box of every glyph Common/Icons.qml names, in units of 1/1000 em:
// `w`/`h` are its size, `cx`/`cy` the centre of the ink measured from the pen
// origin (x rightwards, y up from the baseline). Widgets/Icon.qml scales each
// glyph so max(w, h) fills its box and puts (cx, cy) at the box's centre.
//
// Measured from: /nix/store/vq963a091mjbcybcfsxajrrq6h0rrs85-berkeley-mono-1.0.0/share/fonts/truetype/BerkeleyMonoNerdFont-Regular.ttf
Singleton {
    // Used for a glyph nobody measured - a square filling the cell, which is
    // what setting a font size and hoping would have given anyway.
    readonly property var fallback: ({
        w: 1000,
        h: 1000,
        cx: 500,
        cy: 500
    })

    readonly property var ink: ({
        "": { w: 600, h: 334, cx: 300, cy: 356 },  // U+0F244 _544
        "": { w: 600, h: 334, cx: 300, cy: 356 },  // U+0F243 _543
        "": { w: 600, h: 334, cx: 300, cy: 356 },  // U+0F242 _542
        "": { w: 600, h: 334, cx: 300, cy: 356 },  // U+0F241 _541
        "": { w: 600, h: 334, cx: 300, cy: 356 },  // U+0F240 _540
        "": { w: 600, h: 1114, cx: 301, cy: 356 },  // U+0F0E7 bolt
        "󰂑": { w: 600, h: 998, cx: 300, cy: 356 },  // U+F0091 battery-unknown
        "󰤯": { w: 600, h: 476, cx: 300, cy: 356 },  // U+F092F wifi-strength-outline
        "󰤟": { w: 600, h: 476, cx: 300, cy: 356 },  // U+F091F wifi-strength-1
        "󰤢": { w: 600, h: 476, cx: 300, cy: 356 },  // U+F0922 wifi-strength-2
        "󰤥": { w: 600, h: 476, cx: 300, cy: 356 },  // U+F0925 wifi-strength-3
        "󰤨": { w: 600, h: 476, cx: 300, cy: 356 },  // U+F0928 wifi-strength-4
        "󰤮": { w: 600, h: 516, cx: 300, cy: 356 },  // U+F092E wifi-strength-off-outline
        "󰀂": { w: 600, h: 574, cx: 300, cy: 356 },  // U+F0002 access-point-network
        "󰕿": { w: 600, h: 1068, cx: 300, cy: 356 },  // U+F057F volume-low
        "󰖀": { w: 600, h: 714, cx: 300, cy: 356 },  // U+F0580 volume-medium
        "󰕾": { w: 600, h: 584, cx: 300, cy: 356 },  // U+F057E volume-high
        "󰝟": { w: 600, h: 506, cx: 300, cy: 356 },  // U+F075F volume-mute
        "󰋋": { w: 600, h: 634, cx: 300, cy: 356 },  // U+F02CB headphones.1
        "󰋎": { w: 600, h: 734, cx: 300, cy: 356 },  // U+F02CE headset
        "󰂯": { w: 600, h: 944, cx: 300, cy: 356 },  // U+F00AF bluetooth
        "󰂱": { w: 600, h: 666, cx: 300, cy: 356 },  // U+F00B1 bluetooth-connect
        "󰂲": { w: 600, h: 748, cx: 300, cy: 356 },  // U+F00B2 bluetooth-off
        "󰍉": { w: 600, h: 600, cx: 300, cy: 356 },  // U+F0349 magnify
        "󰣆": { w: 600, h: 544, cx: 300, cy: 356 },  // U+F08C6 application
        "󰆒": { w: 600, h: 732, cx: 300, cy: 356 },  // U+F0192 content-paste
        "󰋩": { w: 600, h: 600, cx: 300, cy: 356 },  // U+F02E9 image.1
        "󰅂": { w: 600, h: 970, cx: 300, cy: 356 },  // U+F0142 chevron-right.2
        "󰏘": { w: 600, h: 600, cx: 300, cy: 356 }  // U+F03D8 palette
    })
}
