"""Measure every Nerd Font glyph in Icons.qml and emit Common/IconMetrics.qml.

Driven by tools/gen-icon-metrics.sh, which resolves the font Theme.fontIcon
actually renders with. Glyphs are discovered rather than listed: anything in the
private use areas Nerd Fonts patch into counts, so adding an icon to Icons.qml
and re-running this is the whole workflow.

Numbers are per 1000 em regardless of the font's own unitsPerEm, which is what
Widgets/Icon.qml assumes when it turns them into pixels.
"""

import sys

from fontTools.pens.boundsPen import BoundsPen
from fontTools.ttLib import TTFont

# The two private use areas Nerd Fonts patch into. Everything outside them in
# Icons.qml is ordinary text - a workspace number, a "?" - and needs no scaling.
PUA = ((0xE000, 0xF8FF), (0xF0000, 0xFFFFD))


def is_glyph(ch):
    return any(lo <= ord(ch) <= hi for lo, hi in PUA)


def main(font_path, icons_path, out_path):
    font = TTFont(font_path)
    cmap = font.getBestCmap()
    glyphs = font.getGlyphSet()
    hmtx = font["hmtx"]
    # Every measurement is rescaled to a 1000 unit em so Icon.qml can divide by a
    # constant instead of importing the font's own upm.
    scale = 1000.0 / font["head"].unitsPerEm

    source = open(icons_path, encoding="utf-8").read()
    # dict, not set: keeps the order the glyphs appear in Icons.qml, so a diff of
    # the generated file reads like a diff of the ramps that produced it.
    chars = {c: None for c in source if is_glyph(c)}

    rows = []
    for ch in chars:
        name = cmap.get(ord(ch))
        if name is None:
            print(f"gen-icon-metrics: U+{ord(ch):05X} is missing from the font", file=sys.stderr)
            continue
        pen = BoundsPen(glyphs)
        glyphs[name].draw(pen)
        if pen.bounds is None:
            print(f"gen-icon-metrics: U+{ord(ch):05X} ({name}) draws nothing", file=sys.stderr)
            continue
        x0, y0, x1, y1 = (v * scale for v in pen.bounds)
        rows.append({
            "char": ch,
            "code": ord(ch),
            "name": name,
            # Ink box, not the advance: the advance is the monospace cell and is
            # identical for every glyph, which is exactly the information that
            # made them look mismatched in the first place.
            "w": round(x1 - x0),
            "h": round(y1 - y0),
            # Centre of the ink, measured from the pen origin: x rightwards, y up
            # from the baseline. Icon.qml lands this on the centre of its box.
            "cx": round((x0 + x1) / 2),
            "cy": round((y0 + y1) / 2),
            "advance": round(hmtx[name][0] * scale),
        })

    lines = [
        "pragma Singleton",
        "",
        "import Quickshell",
        "",
        "// GENERATED by tools/gen-icon-metrics.sh - do not edit by hand.",
        "//",
        "// The ink box of every glyph Common/Icons.qml names, in units of 1/1000 em:",
        "// `w`/`h` are its size, `cx`/`cy` the centre of the ink measured from the pen",
        "// origin (x rightwards, y up from the baseline). Widgets/Icon.qml scales each",
        "// glyph so max(w, h) fills its box and puts (cx, cy) at the box's centre.",
        "//",
        f"// Measured from: {font_path}",
        "Singleton {",
        "    // Used for a glyph nobody measured - a square filling the cell, which is",
        "    // what setting a font size and hoping would have given anyway.",
        "    readonly property var fallback: ({",
        "        w: 1000,",
        "        h: 1000,",
        "        cx: 500,",
        "        cy: 500",
        "    })",
        "",
        "    readonly property var ink: ({",
    ]
    for i, r in enumerate(rows):
        comma = "," if i < len(rows) - 1 else ""
        lines.append(
            f'        "{r["char"]}": {{ w: {r["w"]}, h: {r["h"]}, cx: {r["cx"]}, cy: {r["cy"]} }}{comma}'
            f'  // U+{r["code"]:05X} {r["name"]}'
        )
    lines += ["    })", "}", ""]

    open(out_path, "w", encoding="utf-8").write("\n".join(lines))
    print(f"gen-icon-metrics: {len(rows)} glyphs", file=sys.stderr)


if __name__ == "__main__":
    main(*sys.argv[1:4])
